version: '3.8'

services:
  backend:
    build: ./backend
    container_name: climax_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    working_dir: /app
    command: php artisan serve --host=0.0.0.0 --port=8000

  mobile:
    build: ./mobile
    container_name: climax_mobile
    ports:
      - "19000:19000"
    volumes:
      - ./mobile:/app
    working_dir: /app
    command: npm start
